language: node_js

node_js:
  - "6"

dist: trusty
sudo: required

env:
  - NETWORK=testnet
  - NETWORK=mainnet

before_install:
  - df -h
  - sudo service postgresql stop # Stop default postgres server
  - pg_lsclusters
  - sudo mkdir /db
  - sudo chown -R postgres:postgres /db
  - |
    (
      cd /db
      sudo -u postgres /usr/lib/postgresql/9.6/bin/pg_ctl init -D /db/diskcluster
      sudo -u postgres /usr/lib/postgresql/9.6/bin/pg_ctl start -D /db/diskcluster -l /db/postgres.log
      sudo -u postgres createuser --superuser travis
      sudo -u postgres createdb --owner=travis travis
    )

install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install g++-5
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - g++ --version
  - gcc --version
  - c++ --version
  - cc --version
  - |
    (
      wget https://download.libsodium.org/libsodium/releases/LATEST.tar.gz
      tar -xzf LATEST.tar.gz
      cd libsodium-stable
      ./configure && make -j 2
      sudo make install
    )

script:
  - ./travis.sh

# whitelist long living branches to avoid testing feature branches twice (as branch and as pull request)
branches:
  only:
  - master

notifications:
  email: false
